server:
  port: 8050
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://localhost:3305/shopping?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.gloryh.entity